#Online settings
username: User

#Window settings
fullscreen: no
view_width: 1200
view_height: 800

#Font settings
font: res/fonts/Gudea-Regular.ttf
menu_font: res/fonts/Gudea-Regular.ttf

#Performance settings
steps_per_draw: 1 #More is almost guaranteed to make the game faster, 1 is ideal

#Debug settings
network_debug_mode: no
invincible: no #Feel like exploring ? -> yes
draw_diagnostics: no
verbose_output: no
keep_event_log: no
