#Online settings
username: SETME

#Window settings
fullscreen: no
regen_level_on_death: yes
view_width: 800
view_height: 600

#Gameplay preferences
autouse_health_potions: yes # can toggle in game as well
autouse_mana_potions: yes # can toggle in game as well

#Font settings
font: res/fonts/Gudea-Regular.ttf

#Network settings
ip: localhost
port: 6112

#Speed settings
steps_per_draw: 1 #More is almost guaranteed to make the game faster, 1 is ideal
time_per_step: 14
frame_action_repeat: 1 #Default = 1. Ignored in single player, improves multiplayer latency in exchange for controlability

#Debug settings
network_debug_mode: no
invincible: yes #Feel like exploring ? -> yes
draw_diagnostics: no
verbose_output: no
